nguage: python
python:
  - 2.7
env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - sed -ie "s#travis-4.3.x.cfg#travis-$PLONE_VERSION.x.cfg#" buildout.cfg
  - python bootstrap.py -d
  - bin/buildout -c buildout.cfg -q
script:
  - bin/flake8 setup.py
  - bin/flake8 plone
  - bin/test
