language: python
python: "2.7"
services:
    - memcached
install:
- virtualenv test-env --no-setuptools
- mkdir -p buildout-cache/downloads
- sed -ie "s#travis-4.3.x.cfg#travis-$PLONE_VERSION.x.cfg#" buildout.cfg
- test-env/bin/python bootstrap.py -c travis.cfg
- bin/buildout -N -t 3 -c travis.cfg
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: bin/test
env:
  matrix:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3